# Admin User API Test

### Login
POST http://localhost:8080/api-admin/public/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
client.global.set("token", response.body.token);
%}

### Create user
POST http://localhost:8080/api-admin/user/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "admin100",
  "password": "admin",
  "email": "admin100@hello.world"
}

### Lock user
POST http://localhost:8080/api-admin/user/lock
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 2
}

### Unlock user
POST http://localhost:8080/api-admin/user/unlock
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 2
}

### Search user
GET http://localhost:8080/api-admin/user/search?username=admin
Content-Type: application/json
Authorization: Bearer {{token}}